// app/page.tsx
"use client";

import { useState } from "react";
import { motion } from "framer-motion";

interface Page {
  left: string;
    right: string;
    }

    export default function DosaMenuBook() {
      const pages: Page[] = [
          { left: "Starters", right: "Main Course" },
              { left: "Desserts", right: "Drinks" },
                  { left: "Specials", right: "Combos" },
                    ];

                      const [currentPage, setCurrentPage] = useState(0);
                        const [turning, setTurning] = useState<"left" | "right" | null>(null);

                          const handleTurnRight = () => {
                              if (currentPage < pages.length - 1) {
                                    setTurning("right");
                                          setTimeout(() => {
                                                  setCurrentPage((p) => p + 1);
                                                          setTurning(null);
                                                                }, 800);
                                                                    }
                                                                      };

                                                                        const handleTurnLeft = () => {
                                                                            if (currentPage > 0) {
                                                                                  setTurning("left");
                                                                                        setTimeout(() => {
                                                                                                setCurrentPage((p) => p - 1);
                                                                                                        setTurning(null);
                                                                                                              }, 800);
                                                                                                                  }
                                                                                                                    };

                                                                                                                      return (
                                                                                                                          <div className="flex flex-col items-center justify-center h-screen bg-gradient-to-br from-amber-100 to-amber-200 perspective-[1200px]">
                                                                                                                                <div className="relative w-[340px] h-[340px] flex">
                                                                                                                                        {/* LEFT HALF (Page turning left) */}
                                                                                                                                                <motion.div
                                                                                                                                                          animate={{
                                                                                                                                                                      rotateY: turning === "left" ? -180 : 0,
                                                                                                                                                                                }}
                                                                                                                                                                                          transition={{ duration: 0.8, ease: [0.77, 0, 0.175, 1] }}
                                                                                                                                                                                                    className="w-1/2 h-full bg-gradient-to-b from-orange-200 to-orange-300 rounded-l-full border border-orange-500 shadow-xl flex items-center justify-center cursor-pointer"
                                                                                                                                                                                                              style={{
                                                                                                                                                                                                                          transformOrigin: "right center",
                                                                                                                                                                                                                                      backfaceVisibility: "hidden",
                                                                                                                                                                                                                                                }}
                                                                                                                                                                                                                                                          onClick={handleTurnLeft}
                                                                                                                                                                                                                                                                  >
                                                                                                                                                                                                                                                                            <p className="text-lg font-bold text-brown-700">
                                                                                                                                                                                                                                                                                        {pages[currentPage].left}
                                                                                                                                                                                                                                                                                                  </p>
                                                                                                                                                                                                                                                                                                          </motion.div>

                                                                                                                                                                                                                                                                                                                  {/* RIGHT HALF (Page turning right) */}
                                                                                                                                                                                                                                                                                                                          <motion.div
                                                                                                                                                                                                                                                                                                                                    animate={{
                                                                                                                                                                                                                                                                                                                                                rotateY: turning === "right" ? 180 : 0,
                                                                                                                                                                                                                                                                                                                                                          }}
                                                                                                                                                                                                                                                                                                                                                                    transition={{ duration: 0.8, ease: [0.77, 0, 0.175, 1] }}
                                                                                                                                                                                                                                                                                                                                                                              className="w-1/2 h-full bg-gradient-to-b from-orange-300 to-orange-400 rounded-r-full border border-orange-600 shadow-xl flex items-center justify-center cursor-pointer"
                                                                                                                                                                                                                                                                                                                                                                                        style={{
                                                                                                                                                                                                                                                                                                                                                                                                    transformOrigin: "left center",
                                                                                                                                                                                                                                                                                                                                                                                                                backfaceVisibility: "hidden",
                                                                                                                                                                                                                                                                                                                                                                                                                          }}
                                                                                                                                                                                                                                                                                                                                                                                                                                    onClick={handleTurnRight}
                                                                                                                                                                                                                                                                                                                                                                                                                                            >
                                                                                                                                                                                                                                                                                                                                                                                                                                                      <p className="text-lg font-bold text-brown-800">
                                                                                                                                                                                                                                                                                                                                                                                                                                                                  {pages[currentPage].right}
                                                                                                                                                                                                                                                                                                                                                                                                                                                                            </p>
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                    </motion.div>
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                          </div>

                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                {/* Page Indicator */}
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                      <div className="mt-6 flex gap-2">
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                              {pages.map((_, i) => (
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                        <div
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                    key={i}
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                className={`w-2 h-2 rounded-full ${
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                              i === currentPage ? "bg-orange-600" : "bg-gray-400"
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                          }`}
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                    />
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                            ))}
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                  </div>

                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                        <p className="absolute bottom-10 text-sm text-gray-600">
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                👉 Tap left or right dosa-half to flip pages
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                      </p>
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                          </div>
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                            );
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                            }